### ISSUE TITLE
No auth mechanism defined

### ISSUE THREAD

**Issue by Freyert** [vesln/hippie#28]
`hippie`: 0.4.0

Using basic auth as per the documentation in the README, getting this error:

```
/node_modules/request/lib/auth.js:118
    throw new Error('no auth mechanism defined')
    ^

Error: no auth mechanism defined
    at Auth.onRequest (/home/fulton/Desktop/apic-health/node_modules/request/lib/auth.js:118:11)
    at Request.auth (/home/fulton/Desktop/apic-health/node_modules/request/request.js:1398:14)
    at Request.init (/home/fulton/Desktop/apic-health/node_modules/request/request.js:569:10)
    at new Request (/home/fulton/Desktop/apic-health/node_modules/request/request.js:272:8)
    at request (/home/fulton/Desktop/apic-health/node_modules/request/index.js:56:10)
    at Client.request (/home/fulton/Desktop/apic-health/node_modules/hippie/lib/hippie/client.js:401:3)
    at next (/home/fulton/Desktop/apic-health/node_modules/hippie/lib/hippie/client.js:423:27)
    at Client.setup (/home/fulton/Desktop/apic-health/node_modules/hippie/lib/hippie/client.js:425:5)
    at Client.end (/home/fulton/Desktop/apic-health/node_modules/hippie/lib/hippie/client.js:351:17)
    at Test.<anonymous> (/home/fulton/Desktop/apic-health/src/definitions/security.js:19:4)
```

**Comment by Freyert** [comment]
Turns out I was passing undefined in everywhere.
